version: '3'

services:

  dev-mysql:
    container_name: dev-mysql
    image: mysql:8.0
    restart: always
    volumes:
      - ./temp/mysql/var/lib/mysql:/var/lib/mysql
    ports:
      - 11113:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

  dev-phpmyadmin:
    container_name: dev-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 11112:80
    environment:
      PMA_HOST: dev-mysql
      #PMA_ARBITRARY: 1 # показывать поле "Server" для ввода хоста
