version: '3'

services:

  dockerfile-backend:
    container_name: dockerfile-backend
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./.docker-compose.backend.env:/app/prod.env
      - ./.docker-compose.backend.env:/app/dev.env
    ports:
      - ${APP__PORT}:${APP__PORT}
      - 9229:9229
    command: >
        bash -c "
          yarn build
          # yarn prod-migr-run
          # yarn prod-start
          yarn dev-migr-run
          yarn dev-start"
    depends_on:
      dockerfile-mysql:
        condition: service_healthy

  dockerfile-mysql:
    container_name: dockerfile-mysql
    restart: always
    image: mysql:8.0
    volumes:
      - ./docker/backend/mysql/var/lib/mysql:/var/lib/mysql
    # ports:
      # - 33332:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  dockerfile-phpmyadmin:
    container_name: dockerfile-phpmyadmin
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
      - 33333:80
    environment:
      PMA_HOST: dockerfile-mysql
      #PMA_PORT: 3306
      #PMA_ARBITRARY: 1 # показывать поле "Server" для ввода хоста
